In [1]:
import numpy as np

In [3]:
l = [1,2,4,5,6,7]

In [4]:
np.array(l) # 1-d array

array([1, 2, 4, 5, 6, 7])

In [7]:
l1 = [1,2,3,5,'murali',False,45.5454]

In [12]:
a1= np.array(l1)  # store the data in all strings with higher memory

In [19]:
a2=np.array([[1,2,3], [4,5,6]])#2d array
a2

array([[1, 2, 3],
       [4, 5, 6]])

In [20]:
a3 = np.array([[[1,2,3],[4,5,6],[7,8,6]]]) # 3-D array
a3

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 6]]])

In [21]:
# to find the number of dimentions of array
a1.ndim

1

In [22]:
a2.ndim

2

In [23]:
a3.ndim

3

In [25]:
a1.size

7

In [26]:
a2.size

6

In [27]:
a3.size

9

In [28]:
a1.shape

(7,)

In [31]:
a2.shape  # 2 rows and 3 columns

(2, 3)

In [32]:
a3.shape #  3x3  1 such metrix

(1, 3, 3)

In [39]:
#random generation metric
np.random.randint(2,50)   # 2 to 50 any number

37

In [41]:
np.random.randint(2,50,(3,4))  # generating random metrix 

array([[31, 18,  7, 21],
       [11, 46, 23, 37],
       [34, 41, 23, 30]])

In [42]:
np.random.randint(2,50,(2,3,4))  # generating random metrix 

array([[[44, 47, 35, 26],
        [ 5, 21,  6, 10],
        [33, 30, 27, 18]],

       [[ 8, 15, 16, 48],
        [44, 33, 18, 19],
        [33, 34, 16, 44]]])

In [43]:
np.random.rand(2,3)

array([[0.19258327, 0.12456724, 0.78514001],
       [0.43308168, 0.68355366, 0.87857734]])

In [45]:
a4=np.random.randn(4,4)

In [46]:
a4

array([[ 0.05327443,  0.6997334 ,  0.91573747, -0.08904656],
       [-0.46401563,  0.44369091,  0.01863649,  0.00992036],
       [-0.21175868,  0.05531681, -0.38702705,  0.60951711],
       [-0.44749971, -0.22213775,  0.19582639,  0.86937366]])

In [48]:
a4.reshape(2,8)

array([[ 0.05327443,  0.6997334 ,  0.91573747, -0.08904656, -0.46401563,
         0.44369091,  0.01863649,  0.00992036],
       [-0.21175868,  0.05531681, -0.38702705,  0.60951711, -0.44749971,
        -0.22213775,  0.19582639,  0.86937366]])

In [49]:
a4.reshape(8,2)

array([[ 0.05327443,  0.6997334 ],
       [ 0.91573747, -0.08904656],
       [-0.46401563,  0.44369091],
       [ 0.01863649,  0.00992036],
       [-0.21175868,  0.05531681],
       [-0.38702705,  0.60951711],
       [-0.44749971, -0.22213775],
       [ 0.19582639,  0.86937366]])

In [50]:
a4.reshape(16,1)

array([[ 0.05327443],
       [ 0.6997334 ],
       [ 0.91573747],
       [-0.08904656],
       [-0.46401563],
       [ 0.44369091],
       [ 0.01863649],
       [ 0.00992036],
       [-0.21175868],
       [ 0.05531681],
       [-0.38702705],
       [ 0.60951711],
       [-0.44749971],
       [-0.22213775],
       [ 0.19582639],
       [ 0.86937366]])

In [52]:
a4.reshape(2,-1)  #numpy will calculate factorial

array([[ 0.05327443,  0.6997334 ,  0.91573747, -0.08904656, -0.46401563,
         0.44369091,  0.01863649,  0.00992036],
       [-0.21175868,  0.05531681, -0.38702705,  0.60951711, -0.44749971,
        -0.22213775,  0.19582639,  0.86937366]])

In [54]:
a4.reshape(3,-1)  #numpy will calculate factorial if not factorial it give error

ValueError: cannot reshape array of size 16 into shape (3,newaxis)

In [55]:
a4.reshape(2,2,4)

array([[[ 0.05327443,  0.6997334 ,  0.91573747, -0.08904656],
        [-0.46401563,  0.44369091,  0.01863649,  0.00992036]],

       [[-0.21175868,  0.05531681, -0.38702705,  0.60951711],
        [-0.44749971, -0.22213775,  0.19582639,  0.86937366]]])

In [56]:
a4.reshape(1,1,1,1,2,2,4)

array([[[[[[[ 0.05327443,  0.6997334 ,  0.91573747, -0.08904656],
            [-0.46401563,  0.44369091,  0.01863649,  0.00992036]],

           [[-0.21175868,  0.05531681, -0.38702705,  0.60951711],
            [-0.44749971, -0.22213775,  0.19582639,  0.86937366]]]]]]])

In [57]:
a1

array(['1', '2', '3', '5', 'murali', 'False', '45.5454'], dtype='<U32')

In [58]:
a1[1]

'2'

In [59]:
a1[4:7]

array(['murali', 'False', '45.5454'], dtype='<U32')

In [60]:
a1[2:6:2]

array(['3', 'murali'], dtype='<U32')

In [61]:
a1[::-1]

array(['45.5454', 'False', 'murali', '5', '3', '2', '1'], dtype='<U32')

In [62]:
a2

array([[1, 2, 3],
       [4, 5, 6]])

In [63]:
a2[0]

array([1, 2, 3])

In [66]:
a3[:,1:]

array([[[4, 5, 6],
        [7, 8, 6]]])

In [67]:
a3

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 6]]])

In [70]:
a2[[0,1],1:]

array([[2, 3],
       [5, 6]])

In [71]:
a5 = np.random.randint(2,90,(6,5))
a5

array([[15, 16, 47, 47, 65],
       [ 2, 12, 41, 13, 88],
       [14, 33, 74, 48, 63],
       [42, 79, 38, 63, 39],
       [70, 72, 88, 46,  9],
       [59, 44, 75, 31, 63]])

In [72]:
a5[a5>40]

array([47, 47, 65, 41, 88, 74, 48, 63, 42, 79, 63, 70, 72, 88, 46, 59, 44,
       75, 63])

In [73]:
a5

array([[15, 16, 47, 47, 65],
       [ 2, 12, 41, 13, 88],
       [14, 33, 74, 48, 63],
       [42, 79, 38, 63, 39],
       [70, 72, 88, 46,  9],
       [59, 44, 75, 31, 63]])

In [74]:
a5[0,1]

16

In [75]:
a5[0,1]= 100

In [76]:
a5

array([[ 15, 100,  47,  47,  65],
       [  2,  12,  41,  13,  88],
       [ 14,  33,  74,  48,  63],
       [ 42,  79,  38,  63,  39],
       [ 70,  72,  88,  46,   9],
       [ 59,  44,  75,  31,  63]])

In [80]:
a6 = np.random.randint(0,3,(3,3))

In [81]:
a7 = np.random.randint(0,3,(3,3))

In [83]:
a6 

array([[0, 0, 1],
       [1, 1, 1],
       [1, 1, 2]])

In [84]:
a7

array([[1, 2, 1],
       [0, 0, 1],
       [1, 1, 2]])

In [86]:
a6*a7 # this is not multiplication of matrix it is element wise multiplication

array([[0, 0, 1],
       [0, 0, 1],
       [1, 1, 4]])

In [87]:
a6@a7  # matrix multiplication

array([[1, 1, 2],
       [2, 3, 4],
       [3, 4, 6]])

In [89]:
a6*2

array([[0, 0, 2],
       [2, 2, 2],
       [2, 2, 4]])

In [90]:
a6/0

C:\Users\HP\AppData\Local\Temp/ipykernel_5264/1058679823.py:1: RuntimeWarning: divide by zero encountered in true_divide
  a6/0
C:\Users\HP\AppData\Local\Temp/ipykernel_5264/1058679823.py:1: RuntimeWarning: invalid value encountered in true_divide
  a6/0


array([[nan, nan, inf],
       [inf, inf, inf],
       [inf, inf, inf]])

In [91]:
a6**3

array([[0, 0, 1],
       [1, 1, 1],
       [1, 1, 8]], dtype=int32)

In [94]:
a8= np.zeros((4,4))
a8

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [97]:
a9 = np.ones((4,5))

In [98]:
a9

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [99]:
a9+10

array([[11., 11., 11., 11., 11.],
       [11., 11., 11., 11., 11.],
       [11., 11., 11., 11., 11.],
       [11., 11., 11., 11., 11.]])

In [100]:
a9+np.array([1,2,3,4,5])

array([[2., 3., 4., 5., 6.],
       [2., 3., 4., 5., 6.],
       [2., 3., 4., 5., 6.],
       [2., 3., 4., 5., 6.]])

In [101]:
a9+np.arrray([1,2,3,4])

AttributeError: module 'numpy' has no attribute 'arrray'

In [102]:
np.array([1,2,3,4])

array([1, 2, 3, 4])

In [103]:
np.array([1,2,3,4]).T

array([1, 2, 3, 4])

In [104]:
np.array([1,2,3,4]).T+a9

ValueError: operands could not be broadcast together with shapes (4,) (4,5) 

In [105]:
np.array([[1,2,3,4]]).T+a9

array([[2., 2., 2., 2., 2.],
       [3., 3., 3., 3., 3.],
       [4., 4., 4., 4., 4.],
       [5., 5., 5., 5., 5.]])

In [106]:
np.array([[1,2,3,4]]).T

array([[1],
       [2],
       [3],
       [4]])

In [107]:
a6

array([[0, 0, 1],
       [1, 1, 1],
       [1, 1, 2]])

In [108]:
a6.T

array([[0, 1, 1],
       [0, 1, 1],
       [1, 1, 2]])

In [109]:
a5

array([[ 15, 100,  47,  47,  65],
       [  2,  12,  41,  13,  88],
       [ 14,  33,  74,  48,  63],
       [ 42,  79,  38,  63,  39],
       [ 70,  72,  88,  46,   9],
       [ 59,  44,  75,  31,  63]])

In [110]:
np.sqrt(a5)

array([[ 3.87298335, 10.        ,  6.8556546 ,  6.8556546 ,  8.06225775],
       [ 1.41421356,  3.46410162,  6.40312424,  3.60555128,  9.38083152],
       [ 3.74165739,  5.74456265,  8.60232527,  6.92820323,  7.93725393],
       [ 6.4807407 ,  8.88819442,  6.164414  ,  7.93725393,  6.244998  ],
       [ 8.36660027,  8.48528137,  9.38083152,  6.78232998,  3.        ],
       [ 7.68114575,  6.63324958,  8.66025404,  5.56776436,  7.93725393]])

In [111]:
np.exp(a5)

array([[3.26901737e+06, 2.68811714e+43, 2.58131289e+20, 2.58131289e+20,
        1.69488924e+28],
       [7.38905610e+00, 1.62754791e+05, 6.39843494e+17, 4.42413392e+05,
        1.65163625e+38],
       [1.20260428e+06, 2.14643580e+14, 1.37338298e+32, 7.01673591e+20,
        2.29378316e+27],
       [1.73927494e+18, 2.03828107e+34, 3.18559318e+16, 2.29378316e+27,
        8.65934004e+16],
       [2.51543867e+30, 1.85867175e+31, 1.65163625e+38, 9.49611942e+19,
        8.10308393e+03],
       [4.20121040e+25, 1.28516001e+19, 3.73324200e+32, 2.90488497e+13,
        2.29378316e+27]])

In [112]:
list(range(0,10,2))

[0, 2, 4, 6, 8]

In [113]:
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [114]:
np.arange(1,10,2.5)

array([1. , 3.5, 6. , 8.5])

In [115]:
np.arange(1,10.7,2.5)

array([1. , 3.5, 6. , 8.5])

In [116]:
np.linspace(2,3,num=50)

array([2.        , 2.02040816, 2.04081633, 2.06122449, 2.08163265,
       2.10204082, 2.12244898, 2.14285714, 2.16326531, 2.18367347,
       2.20408163, 2.2244898 , 2.24489796, 2.26530612, 2.28571429,
       2.30612245, 2.32653061, 2.34693878, 2.36734694, 2.3877551 ,
       2.40816327, 2.42857143, 2.44897959, 2.46938776, 2.48979592,
       2.51020408, 2.53061224, 2.55102041, 2.57142857, 2.59183673,
       2.6122449 , 2.63265306, 2.65306122, 2.67346939, 2.69387755,
       2.71428571, 2.73469388, 2.75510204, 2.7755102 , 2.79591837,
       2.81632653, 2.83673469, 2.85714286, 2.87755102, 2.89795918,
       2.91836735, 2.93877551, 2.95918367, 2.97959184, 3.        ])

In [117]:
np.linspace(2,3,num=50,retstep=True)

(array([2.        , 2.02040816, 2.04081633, 2.06122449, 2.08163265,
        2.10204082, 2.12244898, 2.14285714, 2.16326531, 2.18367347,
        2.20408163, 2.2244898 , 2.24489796, 2.26530612, 2.28571429,
        2.30612245, 2.32653061, 2.34693878, 2.36734694, 2.3877551 ,
        2.40816327, 2.42857143, 2.44897959, 2.46938776, 2.48979592,
        2.51020408, 2.53061224, 2.55102041, 2.57142857, 2.59183673,
        2.6122449 , 2.63265306, 2.65306122, 2.67346939, 2.69387755,
        2.71428571, 2.73469388, 2.75510204, 2.7755102 , 2.79591837,
        2.81632653, 2.83673469, 2.85714286, 2.87755102, 2.89795918,
        2.91836735, 2.93877551, 2.95918367, 2.97959184, 3.        ]),
 0.02040816326530612)

In [119]:
np.logspace(2,4,num=4,base=10)

array([  100.        ,   464.15888336,  2154.43469003, 10000.        ])

In [120]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

## Data Visulation

In [122]:
!pip install cufflinks



[notice] A new release of pip available: 22.2.1 -> 22.2.2
[notice] To update, run: python.exe -m pip install --upgrade pip



     ---------------------------------------- 81.7/81.7 kB 1.5 MB/s eta 0:00:00
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'done'
     ---------------------------------------- 15.2/15.2 MB 1.2 MB/s eta 0:00:00
  Created wheel for cufflinks: filename=cufflinks-0.17.3-py3-none-any.whl size=68734 sha256=b72e5af0857506db0fd51c295c60c4967b94ed25b9e63eaff30b2e5356daf9ce
  Stored in directory: c:\users\hp\appdata\local\pip\cache\wheels\29\b4\f8\2fd2206eeeba6ccad8167e4e8894b8c4ec27bf1342037fd136
Successfully built cufflinks


In [123]:
import cufflinks as cf
import pandas as pd
import numpy as np
import seaborn as sns

In [124]:
cf.go_offline()

In [125]:
np.random.randn(100,3)

array([[ 8.19775237e-01,  1.20703005e+00,  1.69890144e-01],
       [ 1.96538157e-01,  9.76454713e-01,  1.18261424e-01],
       [-9.98745124e-01, -9.97159151e-01, -6.72529493e-01],
       [-5.26441080e-02,  5.27326683e-01,  3.35587452e-01],
       [-5.24717458e-01, -6.86566640e-01, -6.30095732e-01],
       [ 9.36930403e-02, -2.64097397e-01, -1.78698204e-01],
       [-4.64979971e-01, -9.39949302e-01, -6.41630561e-01],
       [-5.45301030e-01,  5.19999470e-02,  3.96506362e-01],
       [-2.23778110e+00, -7.28692243e-01, -1.08533169e-01],
       [ 1.29213515e+00, -1.27114513e-01,  1.45830324e+00],
       [ 1.22351592e-03, -2.22107295e+00, -1.84422458e+00],
       [ 5.77131565e-01, -6.71715590e-01,  1.24958470e+00],
       [-1.31151652e+00,  7.29470802e-01,  5.59887943e-01],
       [ 9.06891123e-01,  4.58236246e-01, -6.72157013e-01],
       [-2.28810127e+00, -7.08374289e-01,  5.20561528e-01],
       [ 1.44900407e+00, -9.03952226e-01, -1.27984768e-01],
       [ 3.99771555e-02,  9.00508366e-02

In [128]:
df =pd.DataFrame(np.random.randn(100,3),columns=['A','B','C'])
df

A         B         C
0   0.550515  0.354774 -1.403379
1   1.193644 -0.690451 -0.148493
2   0.490971 -1.431076  0.374895
3   0.986205 -0.856759  1.191116
4   0.327939 -1.163552  0.874100
..       ...       ...       ...
95  1.678553  0.882561  0.853184
96 -1.150879 -1.135520 -0.380926
97  0.836306  0.591842 -1.239338
98  1.684363  0.376503  2.073322
99 -0.666603 -0.010482  1.520591

[100 rows x 3 columns]

In [129]:
df.iplot()

In [136]:
df1 = pd.DataFrame(np.random.randint(3,100,(100,1)))

In [137]:
df1

0
0   48
1   72
2   59
3   36
4   86
..  ..
95  59
96  20
97  86
98   6
99  11

[100 rows x 1 columns]

In [138]:
df1.iplot()

In [139]:
df

A         B         C
0   0.550515  0.354774 -1.403379
1   1.193644 -0.690451 -0.148493
2   0.490971 -1.431076  0.374895
3   0.986205 -0.856759  1.191116
4   0.327939 -1.163552  0.874100
..       ...       ...       ...
95  1.678553  0.882561  0.853184
96 -1.150879 -1.135520 -0.380926
97  0.836306  0.591842 -1.239338
98  1.684363  0.376503  2.073322
99 -0.666603 -0.010482  1.520591

[100 rows x 3 columns]

In [141]:
df.iplot(x= 'A',y='B',mode='markers')

In [143]:
df2 =sns.load_dataset('titanic')

In [144]:
df2.head()

survived  pclass     sex   age  sibsp  parch     fare embarked  class  \
0         0       3    male  22.0      1      0   7.2500        S  Third   
1         1       1  female  38.0      1      0  71.2833        C  First   
2         1       3  female  26.0      0      0   7.9250        S  Third   
3         1       1  female  35.0      1      0  53.1000        S  First   
4         0       3    male  35.0      0      0   8.0500        S  Third   

     who  adult_male deck  embark_town alive  alone  
0    man        True  NaN  Southampton    no  False  
1  woman       False    C    Cherbourg   yes  False  
2  woman       False  NaN  Southampton   yes   True  
3  woman       False    C  Southampton   yes  False  
4    man        True  NaN  Southampton    no   True

In [145]:
df2.iplot(x='age',y='fare',mode='markers')

In [146]:
df2.iplot(x='age',y='pclass',mode='markers')

In [147]:
df2.iplot(x='fare',y='pclass',mode='markers')

In [148]:
df2.head()

survived  pclass     sex   age  sibsp  parch     fare embarked  class  \
0         0       3    male  22.0      1      0   7.2500        S  Third   
1         1       1  female  38.0      1      0  71.2833        C  First   
2         1       3  female  26.0      0      0   7.9250        S  Third   
3         1       1  female  35.0      1      0  53.1000        S  First   
4         0       3    male  35.0      0      0   8.0500        S  Third   

     who  adult_male deck  embark_town alive  alone  
0    man        True  NaN  Southampton    no  False  
1  woman       False    C    Cherbourg   yes  False  
2  woman       False  NaN  Southampton   yes   True  
3  woman       False    C  Southampton   yes  False  
4    man        True  NaN  Southampton    no   True

In [149]:
df2.iplot(kind='bar',x='sex',y='survived')