In [29]:
import pandas as pd

In [30]:
#Creating Dictionary
data = {'name' : ['sudh','krish','hitesh','tulesko'],
        'salary' : [100,200,300,400],
        'mail_id' : ['sudhanshu@ineuron.ai','krish@ineuron.ai','hitesh@ineuron.ai','tulesko@ineuron.ai'],
        'addr' : ['blr','blr','blr','mum']
        }

In [31]:
data

{'name': ['sudh', 'krish', 'hitesh', 'tulesko'],
 'salary': [100, 200, 300, 400],
 'mail_id': ['sudhanshu@ineuron.ai',
  'krish@ineuron.ai',
  'hitesh@ineuron.ai',
  'tulesko@ineuron.ai'],
 'addr': ['blr', 'blr', 'blr', 'mum']}

In [32]:
pd.DataFrame(data)

name  salary               mail_id addr
0     sudh     100  sudhanshu@ineuron.ai  blr
1    krish     200      krish@ineuron.ai  blr
2   hitesh     300     hitesh@ineuron.ai  blr
3  tulesko     400    tulesko@ineuron.ai  mum

In [33]:
df=pd.DataFrame(data,index=[4,5,6,7])


In [34]:
df

name  salary               mail_id addr
4     sudh     100  sudhanshu@ineuron.ai  blr
5    krish     200      krish@ineuron.ai  blr
6   hitesh     300     hitesh@ineuron.ai  blr
7  tulesko     400    tulesko@ineuron.ai  mum

In [35]:
#loc takes only named conversions
df.loc[5:6]

name  salary            mail_id addr
5   krish     200   krish@ineuron.ai  blr
6  hitesh     300  hitesh@ineuron.ai  blr

In [36]:
# iloc will consider only default indexes
df.iloc[1:3]

name  salary            mail_id addr
5   krish     200   krish@ineuron.ai  blr
6  hitesh     300  hitesh@ineuron.ai  blr

In [37]:
df.iloc[5:6] #named indexes so iloc will not return anything


Empty DataFrame
Columns: [name, salary, mail_id, addr]
Index: []

In [38]:
df=pd.DataFrame(data)

In [39]:
df

name  salary               mail_id addr
0     sudh     100  sudhanshu@ineuron.ai  blr
1    krish     200      krish@ineuron.ai  blr
2   hitesh     300     hitesh@ineuron.ai  blr
3  tulesko     400    tulesko@ineuron.ai  mum

In [40]:
#New Dataframe Creation
data1 = {'pf_no' : [234,45,54465,656],
         'income_tax' : [234, 565, 767, 6778],
         'mobile_no' : [23543,43543,454,5656],
         'courses' : ['ds','bigdata','web dev','blockchain']
    
}

df1 = pd.DataFrame(data1)
df1

pf_no  income_tax  mobile_no     courses
0    234         234      23543          ds
1     45         565      43543     bigdata
2  54465         767        454     web dev
3    656        6778       5656  blockchain

In [41]:
df

name  salary               mail_id addr
0     sudh     100  sudhanshu@ineuron.ai  blr
1    krish     200      krish@ineuron.ai  blr
2   hitesh     300     hitesh@ineuron.ai  blr
3  tulesko     400    tulesko@ineuron.ai  mum

In [42]:
pd.concat([df,df1])#horizantal concatination

name  salary               mail_id addr    pf_no  income_tax  mobile_no  \
0     sudh   100.0  sudhanshu@ineuron.ai  blr      NaN         NaN        NaN   
1    krish   200.0      krish@ineuron.ai  blr      NaN         NaN        NaN   
2   hitesh   300.0     hitesh@ineuron.ai  blr      NaN         NaN        NaN   
3  tulesko   400.0    tulesko@ineuron.ai  mum      NaN         NaN        NaN   
0      NaN     NaN                   NaN  NaN    234.0       234.0    23543.0   
1      NaN     NaN                   NaN  NaN     45.0       565.0    43543.0   
2      NaN     NaN                   NaN  NaN  54465.0       767.0      454.0   
3      NaN     NaN                   NaN  NaN    656.0      6778.0     5656.0   

      courses  
0         NaN  
1         NaN  
2         NaN  
3         NaN  
0          ds  
1     bigdata  
2     web dev  
3  blockchain

In [43]:
pd.concat([df,df1],axis=1)

name  salary               mail_id addr  pf_no  income_tax  mobile_no  \
0     sudh     100  sudhanshu@ineuron.ai  blr    234         234      23543   
1    krish     200      krish@ineuron.ai  blr     45         565      43543   
2   hitesh     300     hitesh@ineuron.ai  blr  54465         767        454   
3  tulesko     400    tulesko@ineuron.ai  mum    656        6778       5656   

      courses  
0          ds  
1     bigdata  
2     web dev  
3  blockchain

In [44]:
data2 = {'0' : ['sudh','krish','hitesh','tulesko'],
        '1' : [100,200,300,400],
        '2' : ['sudhanshu@ineuron.ai','krish@ineuron.ai','hitesh@ineuron.ai','tulesko@ineuron.ai'],
        '3' : ['blr','blr','blr','mum']
        }
data3 = {'0' : [234,45,54465,656],
         '1' : [234, 565, 767, 6778],
         '2' : [23543,43543,454,5656],
         '3' : ['ds','bigdata','web dev','blockchain']
         }

df2 = pd.DataFrame(data2)
df3 = pd.DataFrame(data3)

In [45]:
pd.concat([df2,df3]) #If column name is same, then NAN values will not come and it will show complete vertical concat operation

0     1                     2           3
0     sudh   100  sudhanshu@ineuron.ai         blr
1    krish   200      krish@ineuron.ai         blr
2   hitesh   300     hitesh@ineuron.ai         blr
3  tulesko   400    tulesko@ineuron.ai         mum
0      234   234                 23543          ds
1       45   565                 43543     bigdata
2    54465   767                   454     web dev
3      656  6778                  5656  blockchain

In [46]:
#Merge Operation
data4 = {'emp_id': [101,102,103,104],
         'salary' : [234,345,200,400],
         'pf' : [23,34,56,78] 
         }

data5 = {'emp_id' : [101,102,104,105],
         'mob_no' : [3434,5656,767,878],
         'house_no' : [345,345,345,56]
         }

df4 = pd.DataFrame(data4)
df5 = pd.DataFrame(data5)

In [47]:
pd.merge(df4,df5) #Basically performs inner join on Common Column (Emp_id)

emp_id  salary  pf  mob_no  house_no
0     101     234  23    3434       345
1     102     345  34    5656       345
2     104     400  78     767       345

In [48]:
pd.merge(df4,df5,how='left')

emp_id  salary  pf  mob_no  house_no
0     101     234  23  3434.0     345.0
1     102     345  34  5656.0     345.0
2     103     200  56     NaN       NaN
3     104     400  78   767.0     345.0

In [49]:
pd.merge(df4,df5,how='right')

emp_id  salary    pf  mob_no  house_no
0     101   234.0  23.0    3434       345
1     102   345.0  34.0    5656       345
2     104   400.0  78.0     767       345
3     105     NaN   NaN     878        56

In [50]:
pd.merge(df4,df5,how='right',on='emp_id')

emp_id  salary    pf  mob_no  house_no
0     101   234.0  23.0    3434       345
1     102   345.0  34.0    5656       345
2     104   400.0  78.0     767       345
3     105     NaN   NaN     878        56

In [51]:
data6 = {'emp_id1': [101,102,103,104],
         'salary' : [234,345,200,400],
         'pf' : [23,34,56,78] 
         }

data7 = {'emp_id2' : [101,102,104,105],
         'mob_no' : [3434,5656,767,878],
         'house_no' : [345,345,345,56]
         }

df6 = pd.DataFrame(data6)
df7 = pd.DataFrame(data7)

In [52]:
pd.merge(df6,df7,left_on='emp_id1',right_on='emp_id2',how='inner')

emp_id1  salary  pf  emp_id2  mob_no  house_no
0      101     234  23      101    3434       345
1      102     345  34      102    5656       345
2      104     400  78      104     767       345

In [53]:
data8 = {'emp_id' : [101,102,103,104],
         'salary' : [234, 345,200,400],
         'pf' : [23,34,56,78],
         }
         
data9  = {'emp_id' : [101,102,104,105],
          'salary' : [234, 345,200,878],
          'house_nu' : [345,345,345,56]
          }

df8 = pd.DataFrame(data8)
df9 = pd.DataFrame(data9)

In [60]:
pd.merge(df8,df9,on=['emp_id','salary']) #based on columns

emp_id  salary  pf  house_nu
0     101     234  23       345
1     102     345  34       345

In [61]:
#Join Operations
data10 = {'emp_id1' : [101,102,103,104],
         'salary1' : [234, 345,200,400],
         'pf' : [23,34,56,78],
         }
         
data11  = {'emp_id2' : [101,102,104,105,123],
          'salary2' : [234, 345,200,878,43],
          'house_nu' : [345,345,345,56,234]
          }

df10 = pd.DataFrame(data10,index=['a','b','c','d'])
df11 = pd.DataFrame(data11,index=['a','b','d','e','f'])

In [62]:
df10

emp_id1  salary1  pf
a      101      234  23
b      102      345  34
c      103      200  56
d      104      400  78

In [63]:
df11

emp_id2  salary2  house_nu
a      101      234       345
b      102      345       345
d      104      200       345
e      105      878        56
f      123       43       234

In [65]:
df10.join(df11) #Match basis index. It will perform join basis row index whereas in Merge it will join basis column Index
# default is left

emp_id1  salary1  pf  emp_id2  salary2  house_nu
a      101      234  23    101.0    234.0     345.0
b      102      345  34    102.0    345.0     345.0
c      103      200  56      NaN      NaN       NaN
d      104      400  78    104.0    200.0     345.0

In [72]:
df_sales = pd.read_csv('C:\\Users\\HP\\Documents\\python-practice\\Pandas_Classes\\data fsds\\sales_data_final.csv')
df_sales

order_id  order_date ship_date       ship_mode  \
0         AG-2011-2040    1/1/2011  1/6/2011  Standard Class   
1        IN-2011-47883    1/1/2011  1/8/2011  Standard Class   
2         HU-2011-1220    1/1/2011  1/5/2011    Second Class   
3      IT-2011-3647632    1/1/2011  1/5/2011    Second Class   
4        IN-2011-47883    1/1/2011  1/8/2011  Standard Class   
...                ...         ...       ...             ...   
51285   CA-2014-115427  12/31/2014  1/4/2015  Standard Class   
51286     MO-2014-2560  12/31/2014  1/5/2015  Standard Class   
51287   MX-2014-110527  12/31/2014  1/2/2015    Second Class   
51288   MX-2014-114783  12/31/2014  1/6/2015  Standard Class   
51289   CA-2014-156720  12/31/2014  1/4/2015  Standard Class   

          customer_name      segment             state        country  market  \
0       Toby Braunhardt     Consumer       Constantine        Algeria  Africa   
1           Joseph Holt     Consumer   New South Wales      Australia    APAC   
2         Annie Thurman     Consumer          Budapest        Hungary    EMEA   
3          Eugene Moren  Home Office         Stockholm         Sweden      EU   
4           Joseph Holt     Consumer   New South Wales      Australia    APAC   
...                 ...          ...               ...            ...     ...   
51285        Erica Bern    Corporate        California  United States      US   
51286         Liz Preis     Consumer  Souss-Massa-Draƒ        Morocco  Africa   
51287  Charlotte Melton     Consumer           Managua      Nicaragua   LATAM   
51288     Tamara Dahlen     Consumer         Chihuahua         Mexico   LATAM   
51289     Jill Matthias     Consumer          Colorado  United States      US   

        region  ...         category sub_category  \
0       Africa  ...  Office Supplies      Storage   
1      Oceania  ...  Office Supplies     Supplies   
2         EMEA  ...  Office Supplies      Storage   
3        North  ...  Office Supplies        Paper   
4      Oceania  ...        Furniture  Furnishings   
...        ...  ...              ...          ...   
51285     West  ...  Office Supplies      Binders   
51286   Africa  ...  Office Supplies      Binders   
51287  Central  ...  Office Supplies       Labels   
51288    North  ...  Office Supplies       Labels   
51289     West  ...  Office Supplies    Fasteners   

                                          product_name sales quantity  \
0                                  Tenex Lockers, Blue   408        2   
1                             Acme Trimmer, High Speed   120        3   
2                              Tenex Box, Single Width    66        4   
3                          Enermax Note Cards, Premium    45        3   
4                           Eldon Light Bulb, Duo Pack   114        5   
...                                                ...   ...      ...   
51285  Cardinal Slant-D Ring Binder, Heavy Gauge Vinyl    14        2   
51286          Wilson Jones Hole Reinforcements, Clear     4        1   
51287           Hon Color Coded Labels, 5000 Label Set    26        3   
51288           Hon Legal Exhibit Labels, Alphabetical     7        1   
51289                              Bagged Rubber Bands     3        3   

       discount    profit  shipping_cost  order_priority  year  
0           0.0  106.1400          35.46          Medium  2011  
1           0.1   36.0360           9.72          Medium  2011  
2           0.0   29.6400           8.17            High  2011  
3           0.5  -26.0550           4.82            High  2011  
4           0.1   37.7700           4.70          Medium  2011  
...         ...       ...            ...             ...   ...  
51285       0.2    4.5188           0.89          Medium  2014  
51286       0.0    0.4200           0.49          Medium  2014  
51287       0.0   12.3600           0.35          Medium  2014  
51288       0.0    0.5600           0.20          Medium  2014  
51289       0.2   -0.6048           0.17   

In [73]:
df_sales.head()

order_id order_date ship_date       ship_mode    customer_name  \
0     AG-2011-2040   1/1/2011  1/6/2011  Standard Class  Toby Braunhardt   
1    IN-2011-47883   1/1/2011  1/8/2011  Standard Class      Joseph Holt   
2     HU-2011-1220   1/1/2011  1/5/2011    Second Class    Annie Thurman   
3  IT-2011-3647632   1/1/2011  1/5/2011    Second Class     Eugene Moren   
4    IN-2011-47883   1/1/2011  1/8/2011  Standard Class      Joseph Holt   

       segment            state    country  market   region  ...  \
0     Consumer      Constantine    Algeria  Africa   Africa  ...   
1     Consumer  New South Wales  Australia    APAC  Oceania  ...   
2     Consumer         Budapest    Hungary    EMEA     EMEA  ...   
3  Home Office        Stockholm     Sweden      EU    North  ...   
4     Consumer  New South Wales  Australia    APAC  Oceania  ...   

          category sub_category                 product_name sales quantity  \
0  Office Supplies      Storage          Tenex Lockers, Blue   408        2   
1  Office Supplies     Supplies     Acme Trimmer, High Speed   120        3   
2  Office Supplies      Storage      Tenex Box, Single Width    66        4   
3  Office Supplies        Paper  Enermax Note Cards, Premium    45        3   
4        Furniture  Furnishings   Eldon Light Bulb, Duo Pack   114        5   

   discount   profit  shipping_cost  order_priority  year  
0       0.0  106.140          35.46          Medium  2011  
1       0.1   36.036           9.72          Medium  2011  
2       0.0   29.640           8.17            High  2011  
3       0.5  -26.055           4.82            High  2011  
4       0.1   37.770           4.70          Medium  2011  

[5 rows x 21 columns]

In [70]:
def profit_flag(a):
    if a >= 0:
        return 'Positive'
    else:
        return 'Negative'

In [69]:
profit_flag(-45)

'Negative'

In [71]:
profit_flag(4)

'Positive'

In [74]:
df_sales.columns

Index(['order_id', 'order_date', 'ship_date', 'ship_mode', 'customer_name',
       'segment', 'state', 'country', 'market', 'region', 'product_id',
       'category', 'sub_category', 'product_name', 'sales', 'quantity',
       'discount', 'profit', 'shipping_cost', 'order_priority', 'year'],
      dtype='object')

In [75]:
#Map,FIlter and Reduce function can be applied on lists but we want to apply such function for Series
df_sales['flag_profit'] = df_sales['profit'].apply(profit_flag)  #Applying our function to each row of Dataframe

In [76]:
df_sales.head()

order_id order_date ship_date       ship_mode    customer_name  \
0     AG-2011-2040   1/1/2011  1/6/2011  Standard Class  Toby Braunhardt   
1    IN-2011-47883   1/1/2011  1/8/2011  Standard Class      Joseph Holt   
2     HU-2011-1220   1/1/2011  1/5/2011    Second Class    Annie Thurman   
3  IT-2011-3647632   1/1/2011  1/5/2011    Second Class     Eugene Moren   
4    IN-2011-47883   1/1/2011  1/8/2011  Standard Class      Joseph Holt   

       segment            state    country  market   region  ... sub_category  \
0     Consumer      Constantine    Algeria  Africa   Africa  ...      Storage   
1     Consumer  New South Wales  Australia    APAC  Oceania  ...     Supplies   
2     Consumer         Budapest    Hungary    EMEA     EMEA  ...      Storage   
3  Home Office        Stockholm     Sweden      EU    North  ...        Paper   
4     Consumer  New South Wales  Australia    APAC  Oceania  ...  Furnishings   

                  product_name sales quantity discount   profit  \
0          Tenex Lockers, Blue   408        2      0.0  106.140   
1     Acme Trimmer, High Speed   120        3      0.1   36.036   
2      Tenex Box, Single Width    66        4      0.0   29.640   
3  Enermax Note Cards, Premium    45        3      0.5  -26.055   
4   Eldon Light Bulb, Duo Pack   114        5      0.1   37.770   

   shipping_cost  order_priority  year flag_profit  
0          35.46          Medium  2011    Positive  
1           9.72          Medium  2011    Positive  
2           8.17            High  2011    Positive  
3           4.82            High  2011    Negative  
4           4.70          Medium  2011    Positive  

[5 rows x 22 columns]

In [77]:
df_sales['len_customer_name'] = df_sales['customer_name'].apply(len)

In [78]:
df_sales.head()

order_id order_date ship_date       ship_mode    customer_name  \
0     AG-2011-2040   1/1/2011  1/6/2011  Standard Class  Toby Braunhardt   
1    IN-2011-47883   1/1/2011  1/8/2011  Standard Class      Joseph Holt   
2     HU-2011-1220   1/1/2011  1/5/2011    Second Class    Annie Thurman   
3  IT-2011-3647632   1/1/2011  1/5/2011    Second Class     Eugene Moren   
4    IN-2011-47883   1/1/2011  1/8/2011  Standard Class      Joseph Holt   

       segment            state    country  market   region  ...  \
0     Consumer      Constantine    Algeria  Africa   Africa  ...   
1     Consumer  New South Wales  Australia    APAC  Oceania  ...   
2     Consumer         Budapest    Hungary    EMEA     EMEA  ...   
3  Home Office        Stockholm     Sweden      EU    North  ...   
4     Consumer  New South Wales  Australia    APAC  Oceania  ...   

                  product_name sales quantity discount   profit  \
0          Tenex Lockers, Blue   408        2      0.0  106.140   
1     Acme Trimmer, High Speed   120        3      0.1   36.036   
2      Tenex Box, Single Width    66        4      0.0   29.640   
3  Enermax Note Cards, Premium    45        3      0.5  -26.055   
4   Eldon Light Bulb, Duo Pack   114        5      0.1   37.770   

   shipping_cost  order_priority  year  flag_profit len_customer_name  
0          35.46          Medium  2011     Positive                15  
1           9.72          Medium  2011     Positive                11  
2           8.17            High  2011     Positive                13  
3           4.82            High  2011     Negative                12  
4           4.70          Medium  2011     Positive                11  

[5 rows x 23 columns]

In [79]:
def quantity_flag(a):
    if a <10:
        return 'low'
    if a >=10 and a<20:
        return 'medium'
    else:
        return 'high'

In [80]:
df_sales.columns

Index(['order_id', 'order_date', 'ship_date', 'ship_mode', 'customer_name',
       'segment', 'state', 'country', 'market', 'region', 'product_id',
       'category', 'sub_category', 'product_name', 'sales', 'quantity',
       'discount', 'profit', 'shipping_cost', 'order_priority', 'year',
       'flag_profit', 'len_customer_name'],
      dtype='object')

In [82]:
df_sales['flag_quantity'] = df_sales['quantity'].apply(quantity_flag)

In [83]:
df_sales.head()

order_id order_date ship_date       ship_mode    customer_name  \
0     AG-2011-2040   1/1/2011  1/6/2011  Standard Class  Toby Braunhardt   
1    IN-2011-47883   1/1/2011  1/8/2011  Standard Class      Joseph Holt   
2     HU-2011-1220   1/1/2011  1/5/2011    Second Class    Annie Thurman   
3  IT-2011-3647632   1/1/2011  1/5/2011    Second Class     Eugene Moren   
4    IN-2011-47883   1/1/2011  1/8/2011  Standard Class      Joseph Holt   

       segment            state    country  market   region  ... sales  \
0     Consumer      Constantine    Algeria  Africa   Africa  ...   408   
1     Consumer  New South Wales  Australia    APAC  Oceania  ...   120   
2     Consumer         Budapest    Hungary    EMEA     EMEA  ...    66   
3  Home Office        Stockholm     Sweden      EU    North  ...    45   
4     Consumer  New South Wales  Australia    APAC  Oceania  ...   114   

  quantity discount   profit shipping_cost  order_priority  year  flag_profit  \
0        2      0.0  106.140         35.46          Medium  2011     Positive   
1        3      0.1   36.036          9.72          Medium  2011     Positive   
2        4      0.0   29.640          8.17            High  2011     Positive   
3        3      0.5  -26.055          4.82            High  2011     Negative   
4        5      0.1   37.770          4.70          Medium  2011     Positive   

   len_customer_name flag_quantity  
0                 15           low  
1                 11           low  
2                 13           low  
3                 12           low  
4                 11           low  

[5 rows x 24 columns]

In [84]:
df_sales['square_quantity'] = df_sales['quantity'].apply(lambda a : a**2)
df_sales

order_id  order_date ship_date       ship_mode  \
0         AG-2011-2040    1/1/2011  1/6/2011  Standard Class   
1        IN-2011-47883    1/1/2011  1/8/2011  Standard Class   
2         HU-2011-1220    1/1/2011  1/5/2011    Second Class   
3      IT-2011-3647632    1/1/2011  1/5/2011    Second Class   
4        IN-2011-47883    1/1/2011  1/8/2011  Standard Class   
...                ...         ...       ...             ...   
51285   CA-2014-115427  12/31/2014  1/4/2015  Standard Class   
51286     MO-2014-2560  12/31/2014  1/5/2015  Standard Class   
51287   MX-2014-110527  12/31/2014  1/2/2015    Second Class   
51288   MX-2014-114783  12/31/2014  1/6/2015  Standard Class   
51289   CA-2014-156720  12/31/2014  1/4/2015  Standard Class   

          customer_name      segment             state        country  market  \
0       Toby Braunhardt     Consumer       Constantine        Algeria  Africa   
1           Joseph Holt     Consumer   New South Wales      Australia    APAC   
2         Annie Thurman     Consumer          Budapest        Hungary    EMEA   
3          Eugene Moren  Home Office         Stockholm         Sweden      EU   
4           Joseph Holt     Consumer   New South Wales      Australia    APAC   
...                 ...          ...               ...            ...     ...   
51285        Erica Bern    Corporate        California  United States      US   
51286         Liz Preis     Consumer  Souss-Massa-Draƒ        Morocco  Africa   
51287  Charlotte Melton     Consumer           Managua      Nicaragua   LATAM   
51288     Tamara Dahlen     Consumer         Chihuahua         Mexico   LATAM   
51289     Jill Matthias     Consumer          Colorado  United States      US   

        region  ... quantity discount    profit shipping_cost order_priority  \
0       Africa  ...        2      0.0  106.1400         35.46         Medium   
1      Oceania  ...        3      0.1   36.0360          9.72         Medium   
2         EMEA  ...        4      0.0   29.6400          8.17           High   
3        North  ...        3      0.5  -26.0550          4.82           High   
4      Oceania  ...        5      0.1   37.7700          4.70         Medium   
...        ...  ...      ...      ...       ...           ...            ...   
51285     West  ...        2      0.2    4.5188          0.89         Medium   
51286   Africa  ...        1      0.0    0.4200          0.49         Medium   
51287  Central  ...        3      0.0   12.3600          0.35         Medium   
51288    North  ...        1      0.0    0.5600          0.20         Medium   
51289     West  ...        3      0.2   -0.6048          0.17         Medium   

       year  flag_profit  len_customer_name  flag_quantity square_quantity  
0      2011     Positive                 15            low               4  
1      2011     Positive                 11            low               9  
2      2011     Positive                 13            low              16  
3      2011     Negative                 12            low               9  
4      2011     Positive                 11            low              25  
...     ...          ...                ...            ...             ...  
51285  2014     Positive                 10            low               4  
51286  2014     Positive                  9            low               1  
51287  2014     Positive                 16            low               9  
51288  2014     Positive                 13            low               1  
51289  2014     Negative                 13            low               9  

[51290 rows x 25 columns]

## Numpy Package

In [85]:
import numpy as np

In [86]:
np.array([1,2,3,4,5])#nd array Converted List into numpy array

array([1, 2, 3, 4, 5])

In [88]:
type(np.array([1,2,3,4,5])) #1D array

numpy.ndarray

In [89]:
np.array([[2,3,4],[4,5,6]])

array([[2, 3, 4],
       [4, 5, 6]])

In [91]:
type(np.array([[2,3,4],[4,5,6]]))# 2d array

numpy.ndarray

In [92]:
np.array([[1,2,3,4],[2,3,4,5]]) #2D Array

array([[1, 2, 3, 4],
       [2, 3, 4, 5]])

In [93]:
#Extracting Data from List
l = [[1,2,3,4],[2,3,4,5]]
print(l[0][0])
print(l[1][3])

1
5


In [94]:
#Similarily it will happen for array as above. Extracting data from Array
a = np.array([[1,2,3,4],[2,3,4,5]])
print(a[0][0])
print(a[1][3])

1
5


In [95]:
a = np.array([3,4,5,6],ndmin=5)
a #5 Brackets in the begining and end (5 dimensions)

array([[[[[3, 4, 5, 6]]]]])

In [96]:
arr = np.array([[1,2,3],[4,5,6],[6,7,8]])

In [97]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [6, 7, 8]])

In [98]:
arr.ndim

2

In [99]:
np.random.randint(1,10,(4,4)) #4,4 is 4 rows and 4 columns and the random numbers will be between 1 and 10

array([[4, 1, 6, 5],
       [2, 3, 1, 2],
       [5, 5, 7, 9],
       [3, 8, 3, 9]])

In [100]:
np.random.randint(1,10,(4,4,2)) #4,4 is 4 rows and 4 columns and the random numbers will be between 1 and 10

array([[[8, 5],
        [3, 2],
        [2, 1],
        [3, 2]],

       [[4, 9],
        [9, 4],
        [9, 8],
        [5, 9]],

       [[9, 7],
        [7, 3],
        [1, 3],
        [2, 9]],

       [[5, 1],
        [3, 5],
        [5, 1],
        [3, 2]]])

In [101]:
np.random.randint(1,10,(2,4,4)) #4,4 is 4 rows and 4 columns and the random numbers will be between 1 and 10

array([[[4, 8, 7, 8],
        [4, 5, 3, 9],
        [2, 5, 6, 7],
        [9, 8, 5, 3]],

       [[7, 3, 1, 6],
        [8, 2, 4, 1],
        [3, 1, 9, 1],
        [1, 2, 1, 3]]])